global_frame: odom
robot_base_frame: base_link
update_frequency: 2
publish_frequency: 2
static_map: false
rolling_window: true
width: 4.0
height: 4.0
resolution: 0.025
origin_x: 0
origin_y: 0

observation_sources: scan
#plugins:
#  - {name: obstacle_layer,   type: "costmap_2d::ObstacleLayer"}
#  - {name: inflation_layer,  type: "costmap_2d::InflationLayer"}

# assuming receiving a cloud from rtabmap_ros/obstacles_detection node
scan: {
  sensor_frame: base_link,
  data_type: LaserScan, 
  topic: scan, 
  marking: true, 
  clearing: true}
