global_frame: odom
robot_base_frame: base_link
update_frequency: 2
publish_frequency: 2
static_map: false
rolling_window: true
width: 4.0
height: 4.0
resolution: 0.025
origin_x: -2
origin_y: -2

observation_sources: point_cloud_sensor
#plugins:
#  - {name: obstacle_layer,   type: "costmap_2d::ObstacleLayer"}
#  - {name: inflation_layer,  type: "costmap_2d::InflationLayer"}

# assuming receiving a cloud from rtabmap_ros/obstacles_detection node
point_cloud_sensor: {
  sensor_frame: base_link,
  data_type: PointCloud2, 
  topic: points_xyzrgb, 
  expected_update_rate: 0.5, 
  marking: true, 
  clearing: true,
  min_obstacle_height: -99999.0,
  max_obstacle_height: 99999.0}